name: Build site

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/**'
  pull_request:
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/**'
  release:
    types: [ published ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:

  build-python-module:
    name: Build source and wheel distributions
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Hatch
        uses: pypa/hatch@257e27e51a6a5616ed08a39a408a21c35c9931bc

      - name: Hatch fmt and type check
        run: |
          hatch fmt --check
          hatch run types:check

      - name: Build sdist and wheel
        run: |
          hatch build

  check-jinja-templates:
    name: Check Jinja2 templates
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Look for disallowed methods
        run: |
          if grep "console.log" src/xemu_perf_renderer/templates/*; then
            exit 1
          fi
          if grep "console.time" src/xemu_perf_renderer/templates/*; then
            exit 1
          fi

  check-javascript:
    name: Check JS files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Biome
        uses: biomejs/setup-biome@v2
        with:
          version: "latest"

      - name: Look for disallowed methods
        run: |
          if grep "console.log" src/xemu_perf_renderer/templates/*; then
            exit 1
          fi
          if grep "console.time" src/xemu_perf_renderer/templates/*; then
            exit 1
          fi

      - name: Run Biome CI check
        run: biome ci src/xemu_perf_renderer/templates

  build-site:
    name: Regenerate the results site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python 3.13
        uses: actions/setup-python@v6
        with:
          python-version: 3.13

      - name: Generate site
        run: |
          pip3 install --break-system-packages .
          xemu-perf-render results -o site

      - name: Upload site artifact
        uses: actions/upload-artifact@v5
        with:
          name: site
          path: site

  deploy-site:
    name: Update the pages site with new content
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: [build-site]
    steps:
      - name: Clone tree
        uses: actions/checkout@v5

      - name: Update pages_deploy branch
        run: |
          git fetch origin --no-recurse-submodules
          git checkout main
          git pull
          git checkout pages_deploy || git checkout -b pages_deploy
          git reset --hard main

      - uses: actions/download-artifact@v5
        with:
          name: site
          path: docs

      - name: Add and commit site changes
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          git add docs
          git config --local user.email "$GITHUB_ACTOR+github-actions@users.noreply.github.com"
          git config --local user.name "$GITHUB_ACTOR via action"
          git commit -m "Update site content" || echo "No changes to commit"
          git push --set-upstream origin pages_deploy -f
